export const queryKeys = {
  clients: "clients",
  client: "client",
  identityProviders: "identityProviders",
  identityProvider: "identityProvider",
  identityResourceProperties: "identityResourceProperties",
  users: "users",
  user: "user",
  userRoles: "userRoles",
  userClaims: "userClaims",
  roles: "roles",
  role: "role",
  rolesList: "rolesList",
  identityResources: "identityResources",
  identityResource: "identityResource",
  apiResources: "apiResources",
  apiResource: "apiResource",
  apiResourceProperties: "apiResourceProperties",
  apiScopes: "apiScopes",
  apiScope: "apiScope",
  apiResourceSecrets: "apiResourceSecrets",
  clientScopes: "clientScopes",
  clientScope: "clientScope",
  clientGrantTypes: "clientGrantTypes",
  clientGrantType: "clientGrantType",
  clientClaims: "clientClaims",
  clientClaim: "clientClaim",
  clientSecrets: "clientSecrets",
  clientSecret: "clientSecret",
  auditLogs: "auditLogs",
  keys: "keys",
  grantTypes: "grantTypes",
  standardClaims: "standardClaims",
  accessTokenTypes: "accessTokenTypes",
  refreshTokenUsages: "refreshTokenUsages",
  refreshTokenExpirations: "refreshTokenExpirations",
  dpopValidationModes: "dpopValidationModes",
  secretTypes: "secretTypes",
  signingAlgorithms: "signingAlgorithms",
  dashboard: "dashboard",
  configurationIssues: "configurationIssues",
  configurationIssuesSummary: "configurationIssuesSummary",
  userExternalApps: "userExternalApps",
  applicationInfo: "applicationInfo",
  userPersistedGrants: "userPersistedGrants",
  roleClaims: "roleClaims",
  roleUsers: "roleUsers",
  csrfToken: "csrfToken",
} as const;

export const queryWithoutCache = {
  cacheTime: 0,
  staleTime: 0,
};
