import { SnippetLanguage } from "@/lib/highlight/highlightCode";

/**
 * Generates the .NET 10 wire-up for a client, derived from the values currently
 * in the client form. The functions here are pure - the tab passes a snapshot
 * in and renders whatever comes out, so the snippets follow unsaved edits.
 *
 * Only the code flow and client credentials scenarios are supported.
 */

/** Scopes that only make sense for a user-facing flow. */
const IDENTITY_ONLY_SCOPES = new Set([
  "openid",
  "profile",
  "email",
  "address",
  "phone",
  "roles",
  "offline_access",
]);

export type SnippetClientConfig = {
  clientId: string;
  scopes: string[];
  requireClientSecret: boolean;
  requirePkce: boolean;
  allowOfflineAccess: boolean;
  requirePushedAuthorization: boolean;
  requireDPoP: boolean;
  redirectUris: string[];
  postLogoutRedirectUris: string[];
};

/**
 * How the application proves its identity at the token endpoint. `jwk` is the
 * private_key_jwt flavour - the client registers a public JWK as its secret and
 * signs an assertion with the matching private key.
 */
export type ClientAuthentication = "shared_secret" | "jwk";

export type SnippetOptions = {
  /** Base address of IdentityServer, e.g. https://localhost:44310 */
  authority: string;
  /** Used for the cookie, the token client and the HttpClient names. */
  appName: string;
  /** Base address of the API the application calls. */
  apiBaseUrl: string;
  /** Read the credential from configuration instead of inlining it in the code. */
  useUserSecrets: boolean;
  clientAuthentication: ClientAuthentication;
};

/** A translatable note rendered below the code of a step. */
export type SnippetMessage = {
  key: string;
  values?: Record<string, string>;
};

export type SnippetBlock = {
  id: string;
  language: SnippetLanguage;
  code: string;
  /** Shown in the block header and used as the download name. */
  fileName?: string;
  isDownloadable?: boolean;
};

export type SnippetStep = {
  id: string;
  titleKey: string;
  descriptionKey?: string;
  blocks: SnippetBlock[];
  notes?: SnippetMessage[];
  warnings?: SnippetMessage[];
};

export type SnippetDocument = {
  steps: SnippetStep[];
};

const PACKAGE_OIDC = "Microsoft.AspNetCore.Authentication.OpenIdConnect";
const PACKAGE_ATM = "Duende.AccessTokenManagement";
const PACKAGE_ATM_OIDC = "Duende.AccessTokenManagement.OpenIdConnect";

/** Configuration section per scenario, so both snippets can live side by side. */
const OIDC_SECTION = "Oidc";
const CLIENT_CREDENTIALS_SECTION = "ClientCredentials";

const secretKey = (section: string) => `${section}:ClientSecret`;
const dPoPKey = (section: string) => `${section}:DPoPJsonWebKey`;
const signingJwkKey = (section: string) => `${section}:SigningJwk`;
const authorityKey = (section: string) => `${section}:Authority`;
const clientIdKey = (section: string) => `${section}:ClientId`;

/** `builder.Configuration["Section:Key"]` as it appears in Program.cs. */
const configuration = (key: string) =>
  `builder.Configuration[${csharpString(key)}]`;

const SECRET_PLACEHOLDER = "<your client secret>";
const JWK_PLACEHOLDER = "<your private JWK as a single line of JSON>";
const DPOP_KEY_PLACEHOLDER = "<a private JWK generated by this application>";

const csharpString = (value: string) =>
  `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

/** Trailing slashes break `new Uri(base)` + relative path composition. */
const trimTrailingSlash = (value: string) => value.replace(/\/+$/, "");

const ensureTrailingSlash = (value: string) =>
  value.endsWith("/") ? value : `${value}/`;

/**
 * ASP.NET Core takes the callback as a path, not a full URI. The form allows
 * values that are not valid absolute URLs (yet), hence the guarded parse.
 */
const derivePath = (uris: string[], fallback: string): string => {
  for (const uri of uris) {
    try {
      const { pathname } = new URL(uri);

      if (pathname && pathname !== "/") {
        return pathname;
      }
    } catch {
      // Not an absolute URI - fall through to the next candidate.
    }
  }

  return fallback;
};

/** Turns a client id into a name usable for cookies and HttpClient registrations. */
export const toApplicationName = (clientId: string): string => {
  const name = clientId
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return name === "" ? "my-app" : name;
};

/**
 * Identity scopes first, API scopes after them, `offline_access` last - the
 * order the scopes are usually written by hand in.
 */
const orderScopes = (scopes: string[], allowOfflineAccess: boolean): string[] => {
  const unique = Array.from(new Set(scopes.filter((scope) => scope !== "")));

  if (allowOfflineAccess && !unique.includes("offline_access")) {
    unique.push("offline_access");
  }

  const weight = (scope: string) => {
    if (scope === "openid") return 0;
    if (scope === "profile") return 1;
    if (scope === "offline_access") return 4;

    return IDENTITY_ONLY_SCOPES.has(scope) ? 2 : 3;
  };

  return unique.sort((left, right) => weight(left) - weight(right));
};

const packageStep = (projectTemplate: string, packages: string[]): SnippetStep => ({
  id: "packages",
  titleKey: "Client.Integration.Steps.Packages",
  descriptionKey: "Client.Integration.Steps.PackagesDescription",
  blocks: [
    {
      id: "packages",
      language: "bash",
      code: [
        `# .NET 10 project created with: dotnet new ${projectTemplate}`,
        ...packages.map((packageId) => `dotnet add package ${packageId}`),
      ].join("\n"),
    },
  ],
});

/**
 * Authority and client id live in appsettings.json rather than in the code, so
 * Program.cs and the assertion service read the same values.
 */
const appSettingsStep = (
  section: string,
  clientConfig: SnippetClientConfig,
  options: SnippetOptions,
): SnippetStep => ({
  id: "appsettings",
  titleKey: "Client.Integration.Steps.Settings",
  descriptionKey: "Client.Integration.Steps.SettingsDescription",
  blocks: [
    {
      id: "appsettings",
      language: "json",
      code: JSON.stringify(
        {
          [section]: {
            Authority: trimTrailingSlash(options.authority),
            ClientId: clientConfig.clientId,
          },
        },
        null,
        2,
      ),
      fileName: "appsettings.json",
    },
  ],
});

/**
 * The client credential, which already exists - it was created on the Secrets
 * tab, so this step only moves it into the application's user secrets.
 */
const credentialStep = (
  section: string,
  clientConfig: SnippetClientConfig,
  options: SnippetOptions,
): SnippetStep | null => {
  if (!clientConfig.requireClientSecret || !options.useUserSecrets) {
    return null;
  }

  const isJwk = options.clientAuthentication === "jwk";

  return {
    id: "credential",
    titleKey: isJwk
      ? "Client.Integration.Steps.SigningKey"
      : "Client.Integration.Steps.Secret",
    descriptionKey: isJwk
      ? "Client.Integration.Steps.SigningKeyDescription"
      : "Client.Integration.Steps.SecretDescription",
    blocks: [
      {
        id: "user-secrets",
        language: "bash",
        code: [
          "dotnet user-secrets init",
          isJwk
            ? `dotnet user-secrets set "${signingJwkKey(section)}" "${JWK_PLACEHOLDER}"`
            : `dotnet user-secrets set "${secretKey(section)}" "${SECRET_PLACEHOLDER}"`,
        ].join("\n"),
      },
    ],
    notes: [
      {
        key: isJwk
          ? "Client.Integration.Notes.PrivateJwkNeverLeavesTheApp"
          : "Client.Integration.Notes.SecretNotStored",
      },
    ],
  };
};

/**
 * The DPoP proof key, which does not exist yet - it belongs to the application
 * alone and is registered nowhere, so it has to be generated first.
 */
const dPoPKeyStep = (
  section: string,
  clientConfig: SnippetClientConfig,
): SnippetStep | null => {
  if (!clientConfig.requireDPoP) {
    return null;
  }

  return {
    id: "dpop-key",
    titleKey: "Client.Integration.Steps.DPoPKey",
    descriptionKey: "Client.Integration.Steps.DPoPKeyDescription",
    blocks: [
      {
        id: "dpop-generate",
        language: "csharp",
        code: [
          "// Run once - for example in a scratch console app - and keep the output",
          "using System.Security.Cryptography;",
          "using System.Text.Json;",
          "using Microsoft.IdentityModel.Tokens;",
          "",
          "var rsa = new RsaSecurityKey(RSA.Create(2048));",
          "var jwk = JsonWebKeyConverter.ConvertFromRSASecurityKey(rsa);",
          'jwk.Alg = "PS256";',
          "",
          "Console.WriteLine(JsonSerializer.Serialize(jwk));",
        ].join("\n"),
      },
      {
        id: "dpop-user-secrets",
        language: "bash",
        code: `dotnet user-secrets set "${dPoPKey(section)}" "${DPOP_KEY_PLACEHOLDER}"`,
      },
    ],
    notes: [{ key: "Client.Integration.Notes.DPoPProofKey" }],
  };
};

const secretExpression = (
  configurationKey: string,
  useUserSecrets: boolean,
): string =>
  useUserSecrets
    ? `builder.Configuration[${csharpString(configurationKey)}]`
    : csharpString(SECRET_PLACEHOLDER);

/**
 * private_key_jwt support: Duende's access token management asks this service
 * for a freshly signed assertion whenever it authenticates at the token
 * endpoint, so the client never sends a shared secret.
 */
const buildClientAssertionService = (
  section: string,
  options: SnippetOptions,
): string => {
  const jwkExpression = options.useUserSecrets
    ? `configuration[${csharpString(signingJwkKey(section))}]!`
    : csharpString(JWK_PLACEHOLDER);

  return [
    "using Duende.AccessTokenManagement;",
    "using Duende.IdentityModel;",
    "using Duende.IdentityModel.Client;",
    "using Microsoft.IdentityModel.JsonWebTokens;",
    "using Microsoft.IdentityModel.Tokens;",
    "",
    "// Signs the private_key_jwt assertion with the private key that belongs to",
    "// the public JWK registered as this client's secret.",
    "public class ClientAssertionService(IConfiguration configuration)",
    "    : IClientAssertionService",
    "{",
    `    private readonly string clientId = configuration[${csharpString(clientIdKey(section))}]!;`,
    `    private readonly string authority = configuration[${csharpString(authorityKey(section))}]!;`,
    "",
    "    private readonly SigningCredentials credentials =",
    `        CreateCredentials(${jwkExpression});`,
    "",
    "    public Task<ClientAssertion?> GetClientAssertionAsync(",
    "        ClientCredentialsClientName? clientName = null,",
    "        TokenRequestParameters? parameters = null,",
    "        CancellationToken ct = default)",
    "    {",
    "        var now = DateTime.UtcNow;",
    "",
    "        var descriptor = new SecurityTokenDescriptor",
    "        {",
    "            Issuer = clientId,",
    "            Audience = authority,",
    "            IssuedAt = now,",
    "            NotBefore = now,",
    "            Expires = now.AddMinutes(1),",
    "            SigningCredentials = credentials,",
    "",
    "            // A fresh jti per assertion - the token endpoint rejects replays",
    "            Claims = new Dictionary<string, object>",
    "            {",
    "                { JwtClaimTypes.JwtId, Guid.NewGuid().ToString() },",
    "                { JwtClaimTypes.Subject, clientId }",
    "            }",
    "        };",
    "",
    "        var jwt = new JsonWebTokenHandler().CreateToken(descriptor);",
    "",
    "        return Task.FromResult<ClientAssertion?>(new ClientAssertion",
    "        {",
    "            Type = OidcConstants.ClientAssertionTypes.JwtBearer,",
    "            Value = jwt",
    "        });",
    "    }",
    "",
    "    // The signing algorithm comes from the key itself - a JWK generated in",
    '    // the Admin UI always carries "alg". The curve is the fallback.',
    "    private static SigningCredentials CreateCredentials(string jwk)",
    "    {",
    "        var key = new JsonWebKey(jwk);",
    "",
    "        var algorithm = key.Alg ?? (key.Crv switch",
    "        {",
    "            JsonWebKeyECTypes.P256 => SecurityAlgorithms.EcdsaSha256,",
    "            JsonWebKeyECTypes.P384 => SecurityAlgorithms.EcdsaSha384,",
    "            JsonWebKeyECTypes.P521 => SecurityAlgorithms.EcdsaSha512,",
    "            _ => SecurityAlgorithms.RsaSha256",
    "        });",
    "",
    "        return new SigningCredentials(key, algorithm);",
    "    }",
    "}",
  ].join("\n");
};

const assertionStep = (
  section: string,
  options: SnippetOptions,
): SnippetStep => ({
  id: "assertion",
  titleKey: "Client.Integration.Steps.Assertion",
  descriptionKey: "Client.Integration.Steps.AssertionDescription",
  blocks: [
    {
      id: "assertion",
      language: "csharp",
      code: buildClientAssertionService(section, options),
      fileName: "ClientAssertionService.cs",
      isDownloadable: true,
    },
  ],
  notes: [
    { key: "Client.Integration.Notes.AssertionServiceNamespace" },
    { key: "Client.Integration.Notes.SigningAlgorithm" },
  ],
});

const buildAuthorizationCodeProgram = (
  clientConfig: SnippetClientConfig,
  options: SnippetOptions,
  scopes: string[],
): string => {
  const useJwkAuth =
    clientConfig.requireClientSecret && options.clientAuthentication === "jwk";

  // Only these two need a managed HttpClient for calling APIs.
  const useApiHttpClient =
    clientConfig.allowOfflineAccess || clientConfig.requireDPoP;

  // private_key_jwt runs through the same library, so it pulls it in as well.
  const useTokenManagement = useApiHttpClient || useJwkAuth;

  const duendeUsings: string[] = [];

  if (useJwkAuth) {
    duendeUsings.push("using Duende.AccessTokenManagement;");
  }

  if (clientConfig.requireDPoP) {
    duendeUsings.push("using Duende.AccessTokenManagement.DPoP;");
  }

  if (useTokenManagement) {
    duendeUsings.push("using Duende.AccessTokenManagement.OpenIdConnect;");
  }

  const usings = [
    ...duendeUsings,
    "using Microsoft.AspNetCore.Authentication.Cookies;",
    "using Microsoft.AspNetCore.Authentication.OpenIdConnect;",
    "using Microsoft.IdentityModel.Tokens;",
  ];

  const cookieOptions = [
    "        // __Host- requires Secure, Path=/ and no Domain - the browser drops",
    "        // the cookie otherwise, so the app has to be served over HTTPS",
    `        options.Cookie.Name = ${csharpString(`__Host-${options.appName}`)};`,
    '        options.Cookie.Path = "/";',
    "        options.Cookie.SecurePolicy = CookieSecurePolicy.Always;",
    "",
    "        // Strict holds as long as IdentityServer and this app share a site",
    "        options.Cookie.SameSite = SameSiteMode.Strict;",
  ];

  if (clientConfig.allowOfflineAccess) {
    cookieOptions.push(
      "",
      "        // Revokes the refresh token when the user signs out",
      "        options.Events.OnSigningOut = async e =>",
      "            await e.HttpContext.RevokeRefreshTokenAsync();",
    );
  }

  const oidcOptions = [
    "        // The discovery document is loaded from",
    `        // ${trimTrailingSlash(options.authority)}/.well-known/openid-configuration`,
    `        options.Authority = ${configuration(authorityKey(OIDC_SECTION))};`,
    "",
    `        options.ClientId = ${configuration(clientIdKey(OIDC_SECTION))};`,
  ];

  if (useJwkAuth) {
    oidcOptions.push(
      "",
      "        // No ClientSecret - ClientAssertionService signs a private_key_jwt",
    );
  } else if (clientConfig.requireClientSecret) {
    oidcOptions.push(
      `        options.ClientSecret = ${secretExpression(secretKey(OIDC_SECTION), options.useUserSecrets)};`,
    );
  }

  oidcOptions.push(
    "",
    '        options.ResponseType = "code";',
    `        options.UsePkce = ${clientConfig.requirePkce ? "true" : "false"};`,
  );

  if (clientConfig.requirePushedAuthorization) {
    oidcOptions.push(
      "        options.PushedAuthorizationBehavior = PushedAuthorizationBehavior.Require;",
    );
  }

  oidcOptions.push(
    "",
    "        // These paths have to match the URIs registered for the client",
    `        options.CallbackPath = ${csharpString(derivePath(clientConfig.redirectUris, "/signin-oidc"))};`,
    `        options.SignedOutCallbackPath = ${csharpString(derivePath(clientConfig.postLogoutRedirectUris, "/signout-callback-oidc"))};`,
    "",
    "        options.Scope.Clear();",
    ...scopes.map((scope) => `        options.Scope.Add(${csharpString(scope)});`),
    "",
    "        options.GetClaimsFromUserInfoEndpoint = true;",
    "        options.SaveTokens = true;",
    "        options.MapInboundClaims = false;",
    "",
    "        options.TokenValidationParameters = new TokenValidationParameters",
    "        {",
    '            NameClaimType = "name",',
    '            RoleClaimType = "role"',
    "        };",
  );

  const tokenManagement: string[] = [];

  if (useTokenManagement) {
    tokenManagement.push("");

    if (clientConfig.requireDPoP) {
      tokenManagement.push(
        "// The client requires DPoP, so the access token is bound to this key",
        "builder.Services.AddOpenIdConnectAccessTokenManagement(options =>",
        "{",
        `    options.DPoPJsonWebKey = DPoPProofKey.Parse(builder.Configuration[${csharpString(dPoPKey(OIDC_SECTION))}]!);`,
        "});",
      );
    } else {
      tokenManagement.push(
        clientConfig.allowOfflineAccess
          ? "// Refreshes the access token in the background using the refresh token"
          : "// Hooks the client assertion into the code exchange",
        "builder.Services.AddOpenIdConnectAccessTokenManagement();",
      );
    }

    if (useJwkAuth) {
      tokenManagement.push(
        "",
        "builder.Services.AddTransient<IClientAssertionService, ClientAssertionService>();",
      );
    }

    if (useApiHttpClient) {
      tokenManagement.push(
        "",
        `builder.Services.AddUserAccessTokenHttpClient(${csharpString(options.appName)}, configureClient: client =>`,
        "{",
        `    client.BaseAddress = new Uri(${csharpString(ensureTrailingSlash(options.apiBaseUrl))});`,
        "});",
      );
    }
  }

  return [
    ...usings,
    "",
    "var builder = WebApplication.CreateBuilder(args);",
    "",
    "builder.Services.AddAuthentication(options =>",
    "    {",
    "        options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;",
    "        options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;",
    "        options.DefaultSignOutScheme = OpenIdConnectDefaults.AuthenticationScheme;",
    "    })",
    "    .AddCookie(options =>",
    "    {",
    ...cookieOptions,
    "    })",
    "    .AddOpenIdConnect(options =>",
    "    {",
    ...oidcOptions,
    "    });",
    ...tokenManagement,
    "",
    "builder.Services.AddAuthorization();",
    "",
    "var app = builder.Build();",
    "",
    "app.UseAuthentication();",
    "app.UseAuthorization();",
    "",
    "app.Run();",
  ].join("\n");
};

export const buildAuthorizationCodeSnippet = (
  clientConfig: SnippetClientConfig,
  options: SnippetOptions,
): SnippetDocument => {
  const scopes = orderScopes(clientConfig.scopes, clientConfig.allowOfflineAccess);

  const useJwkAuth =
    clientConfig.requireClientSecret && options.clientAuthentication === "jwk";

  const packages = [PACKAGE_OIDC];

  if (clientConfig.allowOfflineAccess || clientConfig.requireDPoP || useJwkAuth) {
    packages.push(PACKAGE_ATM_OIDC);
  }

  const steps: SnippetStep[] = [
    packageStep("webapp", packages),
    appSettingsStep(OIDC_SECTION, clientConfig, options),
  ];

  const oidcSteps = [
    credentialStep(OIDC_SECTION, clientConfig, options),
    dPoPKeyStep(OIDC_SECTION, clientConfig),
  ].filter((step) => step !== null);

  steps.push(...oidcSteps);

  const notes: SnippetMessage[] = [];
  const warnings: SnippetMessage[] = [];

  if (!scopes.includes("openid")) {
    warnings.push({ key: "Client.Integration.Notes.MissingOpenIdScope" });
  }

  if (!clientConfig.requirePkce) {
    warnings.push({ key: "Client.Integration.Notes.PkceDisabled" });
  }

  if (!clientConfig.requireClientSecret) {
    notes.push({ key: "Client.Integration.Notes.PublicClient" });
  }

  if (clientConfig.redirectUris.length === 0) {
    warnings.push({ key: "Client.Integration.Notes.NoRedirectUri" });
  }

  if (clientConfig.requireDPoP) {
    notes.push({ key: "Client.Integration.Notes.DPoPRequired" });
  }

  if (!options.useUserSecrets && clientConfig.requireClientSecret) {
    warnings.push({ key: "Client.Integration.Notes.InlineSecret" });
  }

  steps.push({
    id: "program",
    titleKey: "Client.Integration.Steps.Program",
    descriptionKey: "Client.Integration.Steps.ProgramDescription",
    blocks: [
      {
        id: "program",
        language: "csharp",
        code: buildAuthorizationCodeProgram(clientConfig, options, scopes),
        fileName: "Program.cs",
        isDownloadable: true,
      },
    ],
    notes,
    warnings,
  });

  if (useJwkAuth) {
    steps.push(assertionStep(OIDC_SECTION, options));
  }

  return { steps };
};

const buildClientCredentialsProgram = (
  clientConfig: SnippetClientConfig,
  options: SnippetOptions,
  scopes: string[],
): string => {
  const useJwkAuth =
    clientConfig.requireClientSecret && options.clientAuthentication === "jwk";

  const usings = ["using Duende.AccessTokenManagement;"];

  if (clientConfig.requireDPoP) {
    usings.push("using Duende.AccessTokenManagement.DPoP;");
  }

  const clientOptions = [
    '        client.TokenEndpoint = new Uri($"{authority}/connect/token");',
    "",
    `        client.ClientId = ClientId.Parse(${configuration(clientIdKey(CLIENT_CREDENTIALS_SECTION))}!);`,
  ];

  if (useJwkAuth) {
    clientOptions.push(
      "",
      "        // No ClientSecret - ClientAssertionService signs a private_key_jwt",
    );
  } else if (clientConfig.requireClientSecret) {
    const secret = options.useUserSecrets
      ? `${secretExpression(secretKey(CLIENT_CREDENTIALS_SECTION), true)}!`
      : csharpString(SECRET_PLACEHOLDER);

    clientOptions.push(`        client.ClientSecret = ClientSecret.Parse(${secret});`);
  }

  if (scopes.length > 0) {
    clientOptions.push(
      "",
      `        client.Scope = Scope.Parse(${csharpString(scopes.join(" "))});`,
    );
  }

  if (clientConfig.requireDPoP) {
    clientOptions.push(
      "",
      "        // The client requires DPoP - the token is bound to this key",
      `        client.DPoPJsonWebKey = DPoPProofKey.Parse(builder.Configuration[${csharpString(dPoPKey(CLIENT_CREDENTIALS_SECTION))}]!);`,
    );
  }

  return [
    ...usings,
    "",
    "var builder = Host.CreateApplicationBuilder(args);",
    "",
    `var authority = ${configuration(authorityKey(CLIENT_CREDENTIALS_SECTION))}!;`,
    "",
    "// Access tokens are cached here, so they are requested once per lifetime",
    "builder.Services.AddDistributedMemoryCache();",
    "",
    "builder.Services.AddClientCredentialsTokenManagement()",
    `    .AddClient(${csharpString(options.appName)}, client =>`,
    "    {",
    ...clientOptions,
    "    });",
    ...(useJwkAuth
      ? [
          "",
          "builder.Services.AddTransient<IClientAssertionService, ClientAssertionService>();",
        ]
      : []),
    "",
    "// Every request sent through this HttpClient carries a managed access token",
    `builder.Services.AddClientCredentialsHttpClient(${csharpString(options.appName)},`,
    `    ClientCredentialsClientName.Parse(${csharpString(options.appName)}),`,
    "    client =>",
    "    {",
    `        client.BaseAddress = new Uri(${csharpString(ensureTrailingSlash(options.apiBaseUrl))});`,
    "    });",
    "",
    "builder.Services.AddHostedService<ApiWorker>();",
    "",
    "builder.Build().Run();",
  ].join("\n");
};

const buildClientCredentialsWorker = (options: SnippetOptions): string =>
  [
    "public class ApiWorker(",
    "    IHttpClientFactory httpClientFactory,",
    "    ILogger<ApiWorker> logger) : BackgroundService",
    "{",
    "    protected override async Task ExecuteAsync(CancellationToken stoppingToken)",
    "    {",
    `        var client = httpClientFactory.CreateClient(${csharpString(options.appName)});`,
    "",
    "        while (!stoppingToken.IsCancellationRequested)",
    "        {",
    "            // No token handling here - the handler requests and renews it",
    '            var response = await client.GetAsync("data", stoppingToken);',
    "",
    '            logger.LogInformation("API responded with {StatusCode}", response.StatusCode);',
    "",
    "            await Task.Delay(TimeSpan.FromMinutes(1), stoppingToken);",
    "        }",
    "    }",
    "}",
  ].join("\n");

export const buildClientCredentialsSnippet = (
  clientConfig: SnippetClientConfig,
  options: SnippetOptions,
): SnippetDocument => {
  const requestedScopes = Array.from(new Set(clientConfig.scopes));
  const scopes = requestedScopes.filter(
    (scope) => !IDENTITY_ONLY_SCOPES.has(scope),
  );
  const droppedScopes = requestedScopes.filter((scope) =>
    IDENTITY_ONLY_SCOPES.has(scope),
  );

  const useJwkAuth =
    clientConfig.requireClientSecret && options.clientAuthentication === "jwk";

  const steps: SnippetStep[] = [
    packageStep("worker", [PACKAGE_ATM]),
    appSettingsStep(CLIENT_CREDENTIALS_SECTION, clientConfig, options),
  ];

  const machineSteps = [
    credentialStep(CLIENT_CREDENTIALS_SECTION, clientConfig, options),
    dPoPKeyStep(CLIENT_CREDENTIALS_SECTION, clientConfig),
  ].filter((step) => step !== null);

  steps.push(...machineSteps);

  const notes: SnippetMessage[] = [];
  const warnings: SnippetMessage[] = [];

  if (droppedScopes.length > 0) {
    notes.push({
      key: "Client.Integration.Notes.IdentityScopesSkipped",
      values: { scopes: droppedScopes.join(", ") },
    });
  }

  if (scopes.length === 0) {
    warnings.push({ key: "Client.Integration.Notes.NoApiScope" });
  }

  if (!clientConfig.requireClientSecret) {
    warnings.push({ key: "Client.Integration.Notes.MachineClientWithoutSecret" });
  }

  if (clientConfig.requireDPoP) {
    notes.push({ key: "Client.Integration.Notes.DPoPRequired" });
  }

  if (!options.useUserSecrets && clientConfig.requireClientSecret) {
    warnings.push({ key: "Client.Integration.Notes.InlineSecret" });
  }

  steps.push({
    id: "program",
    titleKey: "Client.Integration.Steps.Program",
    descriptionKey: "Client.Integration.Steps.WorkerProgramDescription",
    blocks: [
      {
        id: "program",
        language: "csharp",
        code: buildClientCredentialsProgram(clientConfig, options, scopes),
        fileName: "Program.cs",
        isDownloadable: true,
      },
    ],
    notes,
    warnings,
  });

  if (useJwkAuth) {
    steps.push(assertionStep(CLIENT_CREDENTIALS_SECTION, options));
  }

  steps.push({
    id: "worker",
    titleKey: "Client.Integration.Steps.Worker",
    descriptionKey: "Client.Integration.Steps.WorkerDescription",
    blocks: [
      {
        id: "worker",
        language: "csharp",
        code: buildClientCredentialsWorker(options),
        fileName: "ApiWorker.cs",
        isDownloadable: true,
      },
    ],
  });

  return { steps };
};

/** All blocks of a document joined together, for the "copy everything" action. */
export const flattenSnippetDocument = (document: SnippetDocument): string =>
  document.steps
    .flatMap((step) => step.blocks.map((block) => block.code))
    .join("\n\n");
