// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skoruba.Duende.IdentityServer.Admin.EntityFramework.Shared.DbContexts;

#nullable disable

namespace Skoruba.Duende.IdentityServer.Admin.EntityFramework.SqlServer.Migrations.ConfigurationRules
{
    [DbContext(typeof(ConfigurationRulesDbContext))]
    [Migration("20251212201018_DbInit")]
    partial class DbInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Skoruba.Duende.IdentityServer.Admin.EntityFramework.Admin.Storage.Entities.ConfigurationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Configuration")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FixDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("IssueType")
                        .HasColumnType("int");

                    b.Property<string>("MessageTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.Property<int>("RuleType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RuleType", "ResourceType")
                        .IsUnique();

                    b.ToTable("ConfigurationRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 12, 20, 10, 17, 930, DateTimeKind.Utc).AddTicks(2680),
                            FixDescription = "Go to the client details → Advanced → Grant Types and replace 'implicit' with 'authorization_code'.",
                            IsEnabled = true,
                            IssueType = 0,
                            MessageTemplate = "Client uses obsolete implicit grant flow",
                            ResourceType = 0,
                            RuleType = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 12, 20, 10, 17, 930, DateTimeKind.Utc).AddTicks(2680),
                            FixDescription = "Go to the client details → Advanced → Grant Types and replace 'password' with 'authorization_code' or 'client_credentials'.",
                            IsEnabled = true,
                            IssueType = 0,
                            MessageTemplate = "Client uses obsolete password grant flow",
                            ResourceType = 0,
                            RuleType = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 12, 20, 10, 17, 930, DateTimeKind.Utc).AddTicks(2680),
                            FixDescription = "This client does not use PKCE. Consider enabling PKCE for enhanced security.",
                            IsEnabled = true,
                            IssueType = 1,
                            MessageTemplate = "Client uses authorization code flow without PKCE",
                            ResourceType = 0,
                            RuleType = 2
                        },
                        new
                        {
                            Id = 4,
                            Configuration = "{\"allowLocalhost\": true}",
                            CreatedAt = new DateTime(2025, 12, 12, 20, 10, 17, 930, DateTimeKind.Utc).AddTicks(2680),
                            FixDescription = "Update redirect URIs to use HTTPS protocol. For production environments, HTTP is not secure.",
                            IsEnabled = false,
                            IssueType = 0,
                            MessageTemplate = "Client has redirect URIs not using HTTPS",
                            ResourceType = 0,
                            RuleType = 3
                        },
                        new
                        {
                            Id = 5,
                            Configuration = "{\"prefix\": \"scope_\"}",
                            CreatedAt = new DateTime(2025, 12, 12, 20, 10, 17, 930, DateTimeKind.Utc).AddTicks(2680),
                            FixDescription = "Rename the API Scope to follow the naming convention starting with the required prefix.",
                            IsEnabled = false,
                            IssueType = 1,
                            MessageTemplate = "API Scope name must start with specified prefix",
                            ResourceType = 3,
                            RuleType = 7
                        },
                        new
                        {
                            Id = 6,
                            Configuration = "{\"maxLifetimeSeconds\": 3600}",
                            CreatedAt = new DateTime(2025, 12, 12, 20, 10, 17, 930, DateTimeKind.Utc).AddTicks(2680),
                            FixDescription = "Go to client details → Token and reduce the Access Token Lifetime to the recommended maximum value.",
                            IsEnabled = false,
                            IssueType = 1,
                            MessageTemplate = "Client access token lifetime exceeds recommended maximum",
                            ResourceType = 0,
                            RuleType = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
